### ISSUE TITLE
Project initialization

### ISSUE THREAD

**Issue by michael-fuchs** [fumiX/fuBlog#1]
- [x]  Basic direktory structure for node.js server and vue3-ui.
       Separate main folders in one repo, one for node-server, one for Vue3-UI
- [x] Server
   - [x] Simple single REST service with express and single route/call for first try.
   - [x] Devserver setup to start the server for local development.
- [x] UI
   - [x] Standard-Setup with Vue-CLI, Vite.
   - [x] Access to node-Devserver REST call.

### DoD

Server and client running on developer machine.

**Comment by thooyork** [comment]
basic setup for server and client.
for npm / start scripts please refer readme.md
