### ISSUE TITLE
User Management UI

### ISSUE THREAD

**Issue by michael-fuchs** [fumiX/fuBlog#17]
Administrative UI mit Liste aller Benutzer in der DB (alle, die sich schon mal registriert haben).

Erstmal ohne Suche/Filter/Paging.

Jeder Benutzer in einer Zeile, mit Checkboxen o.ä. für die Berechtigungen.

Benutzer können gelöscht werden. Es genügt im ersten Anlauf richtiges Löschen. Später evtl. nur markieren und damit erneute Registrierung sperren, oder ähnliche Mechanismen.

Datensparsam: Nur absolut relevante Benutzerdaten werden gespeichert -> Email-Adresse.

Berechtigung: Diese Seite sollte über die Nav-Bar ("Administration" ?) erreichbar sein und über das "Adminstrations"-Recht gesichert sein:
* Der Administrations-Punkt wird nur angezeigt, wenn der Benutzer das Recht hat.
* Der Serive sichert den Zugriff auf die Benutzerdaten über das Recht ab.

**Comment by floscher** [comment]
On #14 there is this this view:

![Image](https://user-images.githubusercontent.com/3904348/225259599-4eeb6be6-389d-471e-a288-655efca2e826.png)

Which opens a dialog when the 📝-Button is pressed, but currently non-functional.

@michael-fuchs At the moment we store: First name, last name, profile picture, (blog-internal) username and email. Should name and profile picture be removed then?

**Comment by floscher** [comment]
Bis auf Löschen ist hier alles implementiert. Das würde ich mal in ein eigenes Ticket überführen, selbst das harte Löschen wäre nicht ganz trivial, weil man ja z.B. Posts nicht unbedingt mitlöschen will und momentan alle Posts einen Autor gesetzt haben müssen.

→ #43
