### ISSUE TITLE
Upgrade to Typescript 5.0

### ISSUE THREAD

**Issue by floscher** [fumiX/fuBlog#29]
https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/

https://github.com/fumiX/fuBlog/commit/56047e00ca4668918eac2cb2257a604ed3007b56

**Comment by floscher** [comment]
@thooyork This leads to an error in the client when `npm install` is being run and it is updated to `1.3.11`:
https://github.com/fumiX/fuBlog/blob/a29bce440f7b860a8161db2b6a7de00b91be3aa0/client/package.json#L46

**Comment by thooyork** [comment]
implemented.
