### ISSUE TITLE
404 status page for unmatched URLs, 410 status page for deleted blogposts

### ISSUE THREAD

**Issue by fumiX-RMI** [fumiX/fuBlog#36]
If blog entries are linked or bookmarked from outside the system they may get deleted and still be referenced.
At the moment there will be just a blank screen.

- [x] show 404 Not Found error page for unmatched URL
- [ ] show 410 Gone error page for deleted blogposts

**Comment by floscher** [comment]
There should be a general 404 page, any unmatched URL at the moment leads to a blank page (also currently returns a 200 status code).

I'm not sure, if we should make a special case for deleted blogposts. What would that page display, apart from "Once upon a time there was a blogpost here".

**Comment by floscher** [comment]
On #52 there is a basic 404 page now

**Comment by thooyork** [comment]
improved / cleanup general 404 page
respond 410 on ids that doesn't exist (anymore)
