### ISSUE TITLE
Fix 404 when clicking certain search results

### ISSUE THREAD

**Issue by cb-fumix** [fumiX/fuBlog#57]
- be logged out
- search for something that has search results
- some search results can be clicked
- some search results link to a 404

**Comment by floscher** [comment]
https://github.com/fumiX/fuBlog/blob/1cb479d3c129b95e0a11e9e5293ae6e919c806f3/client/src/router/index.ts#L29
Stimmt, da war `[1-9][0-9]*` gemeint.

**Comment by floscher** [comment]
Ich hab mal pillarjs/path-to-regexp#292 aufgemacht, weil der RegEx eigentlich funktionieren sollte. Vue wertet den ja richtig aus.

**Comment by floscher** [comment]
Ja klar, ist da jetzt nicht kritisch die 0 auszuschließen, das wird wenn ja eh ne Weile dauern, bis das gefixt und releast ist. Von daher gibts für uns vorerst ja auch keine andere Möglichkeit, das auf unserer Seite handzuhaben.
