### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by michael-fuchs** [fumiX/fuBlog#6]
Provide Login for the blog required for creating/editing posts.

The users are intended to be "internal"  users.

- [x] Database table for users (Name, login, credentials or OpenId reference). 
- [ ] Login mechanism working. On the UI the logged in user is displayed (with logout button), and login button is displayed.
- [ ] Technical login process - once decided if simple username/password or OpenId  is  to be used.

NOT: 
* Any extras like profile pictures or other infos for the authors.

**Comment by floscher** [comment]
Closing this in favor of #15
